version: '3.7'

services:
  web:
    build: .
    container_name: my-vite-vue3-app
    restart: always
    environment:
      - VIRTUAL_HOST=91huajian.cn
      - LETSENCRYPT_HOST=91huajian.cn
      - LETSENCRYPT_EMAIL=1584775297@qq.com
    networks:
      - proxy-tier

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy
