version: '3'
services:
  web:
    image: 91huajian-web
    container_name: 91huajian-web-container
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VIRTUAL_HOST=91huajian.cn,www.91huajian.cn
      - LETSENCRYPT_HOST=91huajian.cn,www.91huajian.cn
      - LETSENCRYPT_EMAIL=1584775297@qq.com
    networks:
      - webnet

networks:
  webnet:
